// <auto-generated />
using System;
using Hubtel.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hubtel.Api.Migrations
{
    [DbContext(typeof(WalletContext))]
    [Migration("20241121142659_UpdateWalletColumnNames")]
    partial class UpdateWalletColumnNames
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Hubtel.Api.Entities.Wallet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("wallet_id");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("account_number");

                    b.Property<int>("AccountScheme")
                        .HasColumnType("INTEGER")
                        .HasColumnName("account_scheme");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("wallet_name");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("owner_phone");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER")
                        .HasColumnName("wallet_type");

                    b.HasKey("Id");

                    b.ToTable("Wallets");
                });
#pragma warning restore 612, 618
        }
    }
}
